import { FC, PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'

import Header from '@/widgets/header'
import FooterForm from '@/widgets/footer-form'
import Footer from '@/widgets/footer'

const ubuntu = Ubuntu({ subsets: ['latin'], weight: ['400', '700'] })

import './style/global.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang='en'>
    <body className={ubuntu.className}>
    <Header />
    {children}
    <FooterForm />
    <Footer />
    </body>
    </html>
  )
}

export default RootLayout