import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <hr />
        <h2>RootLayout Start</h2>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          <li>
            <Link href="/dashboard">Dashboard</Link>
            <ul>
              <li>
                <Link href="/dashboard/my">My</Link>
              </li>
              <li>
                <Link href="/dashboard/project">Project</Link>
              </li>
            </ul>
          </li>
          <li>
            <Link prefetch={false} href={{ pathname: '/next', query: { id: 1, age: 20 } }}>Next</Link>
          </li>
        </ul>
        <h2>RootLayout End</h2>
        <hr />

        {children}
      </body>
    </html>
  )
}
